config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'post_books#index'

  resources :post_books, only: [:update, :new, :index, :create, :index, :show, :destroy, :edit]
  resources :users, only: [:new, :index, :show, :edit, :update]
  resources :homes, only: [:index, :about]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_book.rb
class PostBook < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
    validates :opinion, presence: true, length: { maximum: 50 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    has_many :post_books

    attachment :profile_image

    validates :name,
    	 length: { minimum: 2, maximum: 20 },
    	 presence: true

   validates :introduction,
   		length: {maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


	def after_sign_in_path_for(resource)
      user_path(current_user.id)
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/post_books_controller.rb
class PostBooksController < ApplicationController

    before_action :authenticate_user!, except: [:index]

	def new
        @user = current_user
        @users = User.all
		@post_book = PostBook.new
        @post_books = PostBook.all
    end

def create
    @post_book = PostBook.new(post_book_params)
    @post_book.user_id = current_user.id
    if @post_book.save
    redirect_to post_book_path(@post_book.id)
    else
        redirect_to :action => "new"
    end
end

    def edit
        @post_book = PostBook.find(params[:id])
    end

    def index 
    end

    def show
        @user = current_user
        @post_book = PostBook.find(params[:id])
        @post_books = @user.post_books.page(params[:page]).reverse_order
    end

    def destroy
        @post_book = PostBook.find(params[:id])
        @post_book.destroy
        redirect_to :action => "new"
    end

    def update
        @post_book = PostBook.find(params[:id])
        @post_book.update(post_book_params)
        redirect_to post_book_path(@post_book.id)
    end

    private
    def post_book_params
        params.require(:post_book).permit(:title, :opinion, :profile_image)
    end
      def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, except: [:new]

  def index
  	@post_book = PostBook.new
  	@user= current_user
    @users = User.all
  end

  def show
  	@user= current_user
  	@post_book = PostBook.new
  	@user = User.find(params[:id])
  	@post_books = @user.post_books.page(params[:page]).reverse_order
  end

  def edit
  	@post_book = PostBook.new
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  end

  def new
  end

  private
  def user_params
  	params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_books_helper.rb
module PostBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span style="color:#ffffff;">Bookers</span>
    </nav>
<div id="slidemenu">
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="">
        <%= link_to ' Home', user_path(current_user.id) ,class: "glyphicon glyphicon-home" %>
      </li>
      <li class="">
        <%= link_to ' Users', "/users",class: "glyphicon glyphicon-user"  %>
      </li>
      <li class="">
        <%= link_to ' Books', new_post_book_path,class: "glyphicon glyphicon-book"  %>
      </li>
      <li class="">
        <%= link_to " logout", destroy_user_session_path, method: :delete,class: "glyphicon glyphicon-log-out"  %>
      </li>
    <% else %>
      <li class="">
        <%= link_to ' Home', post_books_path ,class: "glyphicon glyphicon-home" %>
      </li>
      <li class="">
        <%= link_to ' About', homes_path,class: "glyphicon glyphicon-link"  %>
      </li>
      <li class="">
        <%= link_to " sign up", new_user_registration_path,class: "glyphicon glyphicon-edit"  %>
      </li>
      <li class="">
        <%= link_to " log in", new_user_session_path,class: "glyphicon glyphicon-log-in"  %>
      </li>
    <% end %>
  </ul>
  </header>
</div>
<%= yield %>
</div>

  </body>
</html>

app/views/post_books/_newbook.html.erb
<%= form_for(post_book, url: post_books_path) do |f| %>
      <h2>New book</h2>
      <div class="form-group has-icon">
        <label class="control-label">Title</label><br />
        <%= f.text_field :title, class:"form-control", placeholder:"" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
      <label class="control-label">Opinion</label><br />
      <%= f.text_area :opinion, class:"form-control", rows:"2", placeholder:"" %><br>
  <%= f.submit "create book", class:"btn btn-primary btn-block " %>
<% end %>

</div>

app/views/post_books/edit.html.erb
<div class='container'>
      <div class="row">
        <div class='top-message col-md-offset-3 col-md-6'>

<h2>Editing Book</h2>

<%= form_for(@post_book) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group has-icon">
        <label class="control-label">Title</label><br />
        <%= f.text_field :title, class:"form-control", placeholder:"" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <label class="control-label">Opinion</label><br />
      <%= f.text_area :opinion, class:"form-control", rows:"3", placeholder:"" %>
    </div>
  </div>
  <br>
  <%= f.submit "Update book", class:"btn btn-primary btn-block" %>
<% end %>
<br>
<div class="pull-left">
	<%= link_to "show",  post_book_path(@post_book.id) %> | <%= link_to "Back", new_post_book_path %>
</div>

</div>
</div>
</div>

app/views/post_books/index.html.erb
<html>
  <head>
    <title>Bookers</title>
  <body>
    <div class='container'>
      <div class="row">
        <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>
<p>In<span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about varioius books!</p>

<div class="btn-wrapper">
<p><%= link_to "Log in", new_user_session_path, class:"text-muted btn btn-info btn-block col-xs-8 " %></p></div>
<p><%= link_to "Sign up", new_user_registration_path, class:"text-muted btn btn-success btn-block col-xs-8 "%></p>
</div>
</div>
</div>
</div>
</div>
  </body>
</html>

app/views/post_books/new.html.erb
<%= form_for(@post_book, url: post_books_path) do |f| %>
  <% if @post_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post_book.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @post_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'users/userinfo', user: @user %>
 <%= render 'post_books/newbook', post_book: @post_book %>  <% end %>

 <div class="container">
    <div class="col-xs-9">
 <h2>
  <span>Books</span>
 </h2>

<table class="table table-condensed">
            <thead>
              <tr>
                <th colspan="1"></th>
                <th>Title</th>
                <th>Opiniton</th>
              </tr>
            </thead>
           <% @post_books.zip(@users).each do |post_book,user| %>
            <tbody>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %></td>
                <td><%= link_to post_book.title, post_book_path(post_book.id) %></td>
                <td><%= post_book.opinion %></td>
              </tr>
            </tbody>
            <% end %>
</table>
</div>
</div>

app/views/post_books/show.html.erb
 <%= render 'users/userinfo', user: @user %>
 <%= render 'post_books/newbook', post_book: @post_book %>

 <div class="container">
    <div class="col-xs-9">

<h2>Book detail</h2>
		<table class="table table-condensed">
            <thead>
              <tr>
              	<th colspan="3"></th>
                <% if @post_book.user == current_user %>
                <th colspan="2"></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <tr>
              	<td><%= attachment_image_tag @post_book.user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %></td></td>
                <td><%= @post_book.title %></td>
                <td><%= @post_book.opinion %></td>
                <% if @post_book.user == current_user %>
                <td><%= link_to "edit", edit_post_book_path(@post_book), class: "btn btn-success"%></td>
                <td><%= link_to "destroy", post_book_path(@post_book), method: :delete,class: "btn btn-danger" %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
          <%= @post_book.user.name %>

        </div>
      </div>

app/views/users/_userinfo.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

<h2>User Info</h2>
<div class="profile-container">
	<table class="table">
		<tbody>
	<tr>
    <th><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %></th></tr>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
	</tbody>
</table>
	<% if user.id == current_user.id %>
        <p><%= link_to "", edit_user_path(user), class: "glyphicon glyphicon-wrench pull-left btn btn-default btn-block" %></p>
    <% end %>
</div>
<br>

app/views/users/edit.html.erb
<div class="container">
	<div class="col-xs-4">

<h2>User info</h2>

<%= form_for(@user) do |f| %>
    <div class="form-group has-icon">
        <label class="control-label" for="inputEmail">Name</label>
        <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
        <div class="form-group has-icon">
    <label class="control-label" for="inputEmail">Image</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
</div>    
	<label class="control-label" for="inputEmail">introduction</label>
        <%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>
    <%= f.submit "Update User", class:"btn btn-primary btn-block " %>
<% end %>
</div>
</div>

app/views/users/index.html.erb
 <%= render 'users/userinfo', user: @user %>
 <%= render 'post_books/newbook', post_book: @post_book %>

 <div class="container">
		<div class="col-xs-9">
<h2>Users</h2>
<table class="table table-condensed">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="1"></th>
        </tr>
            </thead>
           <% @users.each do |user| %>
            <tbody>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td><%= link_to "show", user_path(user.id) %></td>
              </tr>
            </tbody>
            <% end %>
</table>
</div>
</div>

app/views/users/show.html.erb
 <%= render 'users/userinfo', user: @user %>
 <%= render 'post_books/newbook', post_book: @post_book %>
 <div class="container">
		<div class="col-xs-9">
<h2>
  <span>Books</span>
 </h2>

<table class="table table-condensed">
            <thead>
              <tr>
                <th colspan="1"></th>
                <th>Title</th>
                <th>Opiniton</th>
              </tr>
            </thead>
           <% @post_books.each do |post_book| %>
            <tbody>
              <tr>
                <td><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %></td>
                <td><%= link_to post_book.title, post_book_path(post_book.id) %></td>
                <td><%= post_book.opinion %></td>
              </tr>
            </tbody>
            <% end %>
</table>
		</div>
	</div>